//
// Created by lazza on 26/11/2022.
//

#ifndef WAVETABLESYNTHESIZER_APP_SRC_MAIN_CPP_LOWPASSFILTER_H_
#define WAVETABLESYNTHESIZER_APP_SRC_MAIN_CPP_LOWPASSFILTER_H_

class LowPassFilter {

};

#endif //WAVETABLESYNTHESIZER_APP_SRC_MAIN_CPP_LOWPASSFILTER_H_
